// ============================================================================
// Discord CAPTCHA Shield — HTTP entry point (Val Town HTTP trigger)
// ============================================================================
//
// Set this file as the val's HTTP trigger. One deployment shields many Discord
// servers; each server's config + branding lives in SQLite (see guilds.ts).
// Routes (served at the val's endpoint or a mapped custom domain):
//   GET  /g/{guildId}        -> CAPTCHA portal page (per-server branding)
//   POST /g/{guildId}/start  -> verify Turnstile, mint state, return OAuth URL
//   GET  /g/{guildId}/og.png -> cached social card (generated by the cron)
//   GET  /callback           -> validate state, grant the verified role
//   GET  /                   -> redirect to the legacy server, if env-named
//
// Register/manage servers via the guarded admin API (see admin.ts). The single
// OAuth app uses one fixed /callback redirect URI for every server.
// ============================================================================

import { handleVerifyRequest } from "./mod.ts";

export default async function (req: Request): Promise<Response> {
  return await handleVerifyRequest(req);
}
