// ============================================================================
// Discord CAPTCHA Shield — HTTP entry point (Val Town HTTP trigger)
// ============================================================================
//
// Set this file as the val's HTTP trigger. Routes (served at the val's endpoint
// or a mapped custom domain):
//   GET  /          -> CAPTCHA portal page
//   POST /start     -> verify Turnstile token, mint state, return Discord OAuth URL
//   GET  /callback  -> validate state, exchange code, grant the verified role
//   GET  /og.png    -> cached social card (generated by the cron)
//
// To shield a SECOND Discord, clone the whole val and set that copy's env. The
// SQLite tables are project-scoped, so each clone gets isolated storage.
// ============================================================================

import { handleVerifyRequest } from "./mod.ts";
import { loadConfig } from "./config.ts";

export default async function (req: Request): Promise<Response> {
  return await handleVerifyRequest(req, loadConfig());
}
